exclude: openapi_spec.json
repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    stages:
    - commit
    - push
    - manual
    types:
    - text
  - id: check-json
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - args:
    - --maxkb=5000
    id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: debug-statements
  - args:
    - --allow-missing-credentials
    id: detect-aws-credentials
  - id: detect-private-key
  - id: forbid-new-submodules
  - args:
    - --branch
    - develop
    - --branch
    - production
    - --pattern
    - release/.*
    id: no-commit-to-branch
  - id: name-tests-test
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - args:
    - --config=pyproject.toml
    id: black
    types:
    - python
    - pyi
  repo: https://github.com/psf/black
  rev: 22.10.0
- hooks:
  - args:
    - --config=pyproject.toml
    id: pycln
  repo: https://github.com/hadialqattan/pycln
  rev: v2.1.2
- hooks:
  - args:
    - --settings-path=pyproject.toml
    - --filter-files
    files: \.(py)$
    id: isort
    types:
    - cython
    - pyi
    - python
  repo: https://github.com/pycqa/isort
  rev: 5.10.1
- hooks:
  - id: reorder-python-imports
  repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
- hooks:
  - id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v3.2.1
- hooks:
  - args:
    - --global-config=pyproject.toml
    id: autopep8
  repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.0
- hooks:
    - id: commitizen
      stages: [commit-msg]
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.37.0
