# Values here will override previously loaded from settings.toml

[production]                    # All [environments] inherits values from [default] if defined
profile = "prd"
db__port = 8181                  # to merge in value to existing dict, use `__` double underscore lookup.
    [production.api]
    url = "https://httpbin.org/get"
